% tritraining( ...
%     '/home/chang-ning/linux-80211n-csitool-supplementary/log_file/APL.dat', ...
%     '/home/chang-ning/linux-80211n-csitool-supplementary/log_file/location.dat', ...
%     '/home/chang-ning/linux-80211n-csitool-supplementary/log_file/info', ... 
%     '/home/chang-ning/linux-80211n-csitool-supplementary/log_file/output', ...
%     16, 3);
